### ISSUE TITLE
Constant failure at downloading

### ISSUE THREAD

**Issue by David999989** [TortoiseDev/GogoBatcherDio#1]
Every couple of episodes downloads it gives this error :
Attempt failed, retrying....
Attempt failed, retrying....
Traceback (most recent call last):
  File "/storage/emulated/0/Download/GogoBatcherDio-2.2/app.py", line 223, in <module>
    start()
  File "/storage/emulated/0/Download/GogoBatcherDio-2.2/app.py", line 130, in start
    DownloadTheFiles(LoginAndGoToLink(eps,email,password,link,quality),name,startEp,link,quality)
  File "/storage/emulated/0/Download/GogoBatcherDio-2.2/app.py", line 215, in DownloadTheFiles
    link = LoginAndGoToLink(list(range(name,name+1)),mainLink,otherQuality)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LoginAndGoToLink() missing 2 required positional arguments: 'LinkofPath' and 'quality'
I'm using termux and it works fine (thanks for that work u put in to make this time saving tool) other than this error.

**Comment by TortoiseShell04** [comment]
I'll check it out and fix the issue, btw I'm working on a manga scraping tool too, so if you would like something like that it's coming soon

**Comment by TortoiseShell04** [comment]
alright i see the error will fix it now

**Comment by TortoiseShell04** [comment]
Problem Solved!
