### ISSUE TITLE
Not running at all

### ISSUE THREAD

**Issue by David999989** [TortoiseDev/GogoBatcherDio#2]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 221, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[Program finished]
So I feel bad that it's me bringing all the issues with your code. Hope I'm not too heavy on you. And love your work btw. Everything is so simple keep it up chad ♥️♥️.

**Comment by TortoiseShell04** [comment]
is the python version before 3.10, the | operand was introduced in 3.10 so it may not work on earlier versions, if so ill add a file for earlier versions.

**Comment by TortoiseShell04** [comment]
Uploaded a new file, also don't feel bad, if there is an issue with the code it will be brought up one way or another, Thanks for the kind words too! I will leave this issue open incase something goes wrong and will close it after a while

**Comment by David999989** [comment]
> is the python version before 3.10, the | operand was introduced in 3.10 so it may not work on earlier versions, if so ill add a file for earlier versions.

I checked and it's indeed 3.9. if it won't work I'll try it on termux instead of pydroid 3
