### ISSUE TITLE
Finishes without downloading

### ISSUE THREAD

**Issue by David999989** [TortoiseDev/GogoBatcherDio#3]
So I tried the one you made for earlier versions of python and it worked great. But after a couple of days and after typing email and password it doesn't do anything and ends. I tried both the one for earlier versions and the normal one.
2. They're some files that don't download and instead shows: 0.00KB
And thanks for your efforts ❤️

**Comment by David999989** [comment]
> So I tried the one you made for earlier versions of python and it worked great. But after a couple of days and after typing email and password it doesn't do anything and ends. I tried both the one for earlier versions and the normal one. And thanks for your efforts ❤️

Fixed the first issue by changing the main site url from "gogoanimehd.to" to gogoanimehd.io

**Comment by TortoiseShell04** [comment]
ah this issue occurs due to them changing the domain, every so often. I am planning on adding a function to change the domain.
Also no worries I am glad I am able to help someone with my script ❤️.
