### ISSUE TITLE
Cant Download

### ISSUE THREAD

**Issue by Badaryman** [TortoiseDev/GogoBatcherDio#5]
![image](https://github.com/TortoiseShell04/NeoBatcher/assets/154390732/c7268e34-86f8-4e90-834a-00c8550c8601)

when i first ran the code it shows error
![image](https://github.com/TortoiseShell04/NeoBatcher/assets/154390732/08339160-d910-415d-92ed-2c2c31abf9e3)

when i revised it it started working
![image](https://github.com/TortoiseShell04/NeoBatcher/assets/154390732/113090b7-3a10-401a-a24b-4ed84e2bf338)

**Comment by TortoiseShell04** [comment]
you can just remove the str and have it return dict only, its not an issue in execution, just a version issue.

**Comment by Badaryman** [comment]
okay but i cant still download

**Comment by TortoiseShell04** [comment]
Can you send me the error

**Comment by TortoiseShell04** [comment]
anitaku is down right now, in the meantime i will push the latest release of the app

**Comment by Badaryman** [comment]
![image](https://github.com/TortoiseShell04/NeoBatcher/assets/154390732/538fff88-5ff5-43a4-be9f-c121ba1ea598)
same error

**Comment by Badaryman** [comment]
i tried changing it to gogoanime3.net still same

**Comment by Badaryman** [comment]
![image](https://github.com/TortoiseShell04/NeoBatcher/assets/154390732/8df65953-1373-4fa1-84ea-210a9c9213a7)

![image](https://github.com/TortoiseShell04/NeoBatcher/assets/154390732/84118a41-746b-4643-a4f2-fbc6a62c57d5)

**Comment by Badaryman** [comment]
i know now the issue

**Comment by TortoiseShell04** [comment]
Make an account on anitaku and login on the app

**Comment by Badaryman** [comment]
yup done but slow download
