### ISSUE TITLE
Slow Download

### ISSUE THREAD

**Issue by Badaryman** [TortoiseDev/GogoBatcherDio#6]
Is there a way to speed up the downloads? or may add parallel downloads

**Comment by TortoiseShell04** [comment]
The download speed issue is related to the upload speed of the server, so until another source is found sadly this is the best it can get, you can however run multiple instances of the app for mass download

**Comment by Badaryman** [comment]
is there like other way to speed up download or nah? or like cloning it to other something like that

**Comment by Badaryman** [comment]
https://github.com/TechShreyash/AniDL

https://github.com/Prudhvi-pln/udb

i found this too but i want it like in gui

ctto.
